version: "3.8"

services:
  hexo-builder:
    build: .
    container_name: hexo-builder
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm ci && npx hexo clean && npx hexo generate"